"""empty message

Revision ID: 47121665cb72
Revises: a1637357ee88
Create Date: 2020-08-04 12:06:46.956369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47121665cb72'
down_revision = 'a1637357ee88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
